export { default as Header } from "./Header/Header";
export { default as Hero } from "./Hero/Hero";
export { AboutMe } from "./AboutMe/";
export { default as FunDivider } from "./FunDivider/FunDivider";
export { default as ScrollControll } from "./ScrollControll/ScrollControll";
export { default as Skills } from "./Skills/Skills";
export { default as Work } from "./Work/Work";
export { default as Footer } from "./Footer/Footer";
export { default as CursorFollower } from "./CursorFollower/CursorFollower";
export { default as HandEllipse } from "./HandEllipse/HandEllipse";
export { default as DottedLine } from "./DottedLine/DottedLine";
export { default as JoinBox } from "./JoinBox/JoinBox";
export * from "./3dModels";
