export { default as NavBar } from "./NavBar/NavBar";
export { default as Hero } from "./Hero/Hero";
export { default as BtnHamburguesa } from "./BtnHamburguesa/BtnHamburguesa";
export { default as AboutMe } from "./AboutMe/AboutMe";
export { default as FunDivider } from "./FunDivider/FunDivider";
export { default as SmoothScroll } from "./SmoothScroll/SmoothScroll";
export { default as Skills } from "./Skills/Skills";
export { default as Works } from "./Works/Works";
export { default as Footer } from "./Footer/Footer";
export * from "./3dModels";
